; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:attiny45]
; platform = atmelavr
; board = attiny45
; framework = arduino
; lib_deps = 
; 	gyverlibs/Gyver433@^2.1.1
; board_build.f_cpu = 8000000UL
; upload_protocol = custom
; upload_command = ~/.platformio/packages/tool-avrdude/avrdude -C ~/.platformio/packages/tool-avrdude/avrdude.conf -c avrisp -p t45 -P net:192.168.1.158:328 -B 100kHz -U flash:w:${PROJECT_BUILD_DIR}/${PIOENV}/firmware.hex:i
; build_src_filter = 
; 	+<*>
; 	-<esp/>
; 	-<backup>

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_deps = 
	olikraus/U8g2@^2.36.16
	makuna/RTC @ ^2.5.0
	arduino-libraries/NTPClient @ ^3.2.1
	gyverlibs/FileData @ ^1.0.3 
upload_port = /dev/ttyACM0
monitor_speed = 9600
build_src_filter = 
	+<*>
	-<attiny>
	-<esp/backup>
