; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Окружение по умолчанию — пустое, чтобы не собирать всё сразу
default_envs =  attiny13a, attiny45, nodemcuv2
build_cache_dir = ~/.pio/build_cache

; Общие настройки для всех окружений
[common]
monitor_speed = 115200
; pio device monitor --port /dev/ttyACM0 --baud 115200

[env:attiny45]
platform = atmelavr
board = attiny45
monitor_speed = 115200
framework = arduino
board_build.core = tiny
board_build.variant = tinyX5
lib_extra_dirs = ${PROJECT_DIR}/ATTinyCore/avr
lib_deps = 
	gyverlibs/Gyver433@^2.1.1
	gyverlibs/GyverWire@^1.1.4
  	gyverlibs/GyverButton@^3.8
board_build.f_cpu = 8000000UL
upload_protocol = custom
upload_command = ~/.platformio/packages/tool-avrdude/avrdude -C ~/.platformio/packages/tool-avrdude/avrdude.conf -c avrisp -p t45 -P net:192.168.1.158:328 -B 100kHz -U flash:w:${PROJECT_BUILD_DIR}/${PIOENV}/firmware.hex:i
build_src_filter = 
	+<*>
	-<esp/>
	-<attiny13a>
	-<attiny45/backup>

[env:attiny13a]
platform = atmelavr
board = attiny13a
framework = arduino
lib_deps = 
	gyverlibs/Gyver433@^2.1.1
board_build.f_cpu = 9600000UL
upload_protocol = custom
upload_command = ~/.platformio/packages/tool-avrdude/avrdude -C ~/.platformio/packages/tool-avrdude/avrdude.conf -c avrisp -p t13 -P net:192.168.1.158:328 -B 100kHz -U flash:w:${PROJECT_BUILD_DIR}/${PIOENV}/firmware.hex:i
build_src_filter = 
	+<*>
	-<esp/>
	-<attiny45>
	-<attiny13a/backup>

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
board_build.filesystem = littlefs
build_flags = -std=gnu++17
framework = arduino
lib_deps = 
	olikraus/U8g2@^2.36.16
	makuna/RTC @ ^2.5.0
	arduino-libraries/NTPClient @ ^3.2.1
	gyverlibs/FileData @ ^1.0.3 
	gyverlibs/GyverWire @ ^1.1
    me-no-dev/ESPAsyncTCP        ; для ESP8266 (не AsyncTCP!)
    me-no-dev/ESPAsyncWebServer
	bblanchon/ArduinoJson
upload_port = /dev/ttyACM0
monitor_speed = 115200
upload_speed = 460800
build_src_filter = 
	+<*>
	-<attiny45>
	-<attiny13a>
	-<esp/backup>
